const engC1 = [
  {
    question: "What is the opposite of 'big'?",
    A: "Small",
    B: "Tall",
    C: "Large",
    answer: "A",
  },
  {
    question: "Which word means the opposite of 'happy'?",
    A: "Sad",
    B: "Excited",
    C: "Joyful",
    answer: "A",
  },
  {
    question: "What is the plural of 'cat'?",
    A: "Cats",
    B: "Cat",
    C: "Cate",
    answer: "A",
  },
  {
    question: "What is the past tense of 'eat'?",
    A: "Eating",
    B: "Ate",
    C: "Eats",
    answer: "B",
  },
  {
    question: "Which word is a synonym for 'angry'?",
    A: "Happy",
    B: "Mad",
    C: "Glad",
    answer: "B",
  },
  {
    question: "What is the correct spelling?",
    A: "Hapiness",
    B: "Happyness",
    C: "Happiness",
    answer: "C",
  },
  {
    question: "What is the opposite of 'hot'?",
    A: "Cold",
    B: "Warm",
    C: "Cool",
    answer: "A",
  },
  {
    question: "Which word means the opposite of 'slow'?",
    A: "Fast",
    B: "Quick",
    C: "Speedy",
    answer: "A",
  },
  {
    question: "What is the plural of 'dog'?",
    A: "Dog",
    B: "Dogs",
    C: "Doge",
    answer: "B",
  },
  {
    question: "What is the past tense of 'run'?",
    A: "Ran",
    B: "Running",
    C: "Runs",
    answer: "A",
  },
  {
    question: "Which word is a synonym for 'happy'?",
    A: "Gloomy",
    B: "Cheerful",
    C: "Miserable",
    answer: "B",
  },
  {
    question: "What is the correct spelling?",
    A: "Frend",
    B: "Friend",
    C: "Friand",
    answer: "B",
  },
  {
    question: "What is the opposite of 'dark'?",
    A: "Gloomy",
    B: "Bright",
    C: "Shadowy",
    answer: "B",
  },
  {
    question: "Which word means the opposite of 'big'?",
    A: "Tiny",
    B: "Huge",
    C: "Large",
    answer: "A",
  },
  {
    question: "What is the plural of 'fish'?",
    A: "Fishs",
    B: "Fishes",
    C: "Fishies",
    answer: "B",
  },
  {
    question: "What is the past tense of 'jump'?",
    A: "Jumping",
    B: "Jumped",
    C: "Jumps",
    answer: "B",
  },
  {
    question: "Which word is a synonym for 'sad'?",
    A: "Joyful",
    B: "Unhappy",
    C: "Cheerful",
    answer: "B",
  },
  {
    question: "What is the correct spelling?",
    A: "Fruitful",
    B: "Fruitfull",
    C: "Fruitfuul",
    answer: "A",
  },
  {
    question: "What is the opposite of 'dry'?",
    A: "Wet",
    B: "Moist",
    C: "Damp",
    answer: "A",
  },
  {
    question: "Which word means the opposite of 'sweet'?",
    A: "Bitter",
    B: "Sour",
    C: "Salty",
    answer: "A",
  },
];

const engC2 = [
  {
    question: "What is the plural of 'child'?",
    A: "Children",
    B: "Childs",
    C: "Childes",
    answer: "A",
  },
  {
    question: "What is the past participle of 'eat'?",
    A: "Ate",
    B: "Eaten",
    C: "Eating",
    answer: "B",
  },
  {
    question: "Which of the following words is a synonym for 'happy'?",
    A: "Sad",
    B: "Joyful",
    C: "Angry",
    answer: "B",
  },
  {
    question: "What is the correct spelling?",
    A: "Recieve",
    B: "Receive",
    C: "Recive",
    answer: "B",
  },
  {
    question: "Which word is a synonym for 'quick'?",
    A: "Slow",
    B: "Fast",
    C: "Swift",
    answer: "B",
  },
  {
    question: "What is the plural of 'mouse'?",
    A: "Mice",
    B: "Mouses",
    C: "Mices",
    answer: "A",
  },
  {
    question: "What is the past tense of 'see'?",
    A: "Saw",
    B: "Seen",
    C: "Seeing",
    answer: "A",
  },
  {
    question: "Which of the following words is a synonym for 'sad'?",
    A: "Happy",
    B: "Miserable",
    C: "Excited",
    answer: "B",
  },
  {
    question: "What is the correct spelling?",
    A: "Familliar",
    B: "Famliar",
    C: "Familiar",
    answer: "C",
  },
  {
    question: "Which word is a synonym for 'smart'?",
    A: "Intelligent",
    B: "Clever",
    C: "Stupid",
    answer: "A",
  },
  {
    question: "What is the plural of 'goose'?",
    A: "Gooses",
    B: "Geese",
    C: "Geeses",
    answer: "B",
  },
  {
    question: "What is the past tense of 'do'?",
    A: "Did",
    B: "Done",
    C: "Doing",
    answer: "A",
  },
  {
    question: "Which of the following words is a synonym for 'funny'?",
    A: "Serious",
    B: "Humorous",
    C: "Silly",
    answer: "B",
  },
  {
    question: "What is the correct spelling?",
    A: "Occasion",
    B: "Occassion",
    C: "Occasionn",
    answer: "A",
  },
  {
    question: "Which word is a synonym for 'friendly'?",
    A: "Hostile",
    B: "Amiable",
    C: "Aggressive",
    answer: "B",
  },
  {
    question: "What is the plural of 'leaf'?",
    A: "Leaves",
    B: "Leafs",
    C: "Leaflings",
    answer: "A",
  },
  {
    question: "What is the past tense of 'drink'?",
    A: "Drank",
    B: "Drunk",
    C: "Drunked",
    answer: "A",
  },
  {
    question: "Which of the following words is a synonym for 'brave'?",
    A: "Cowardly",
    B: "Courageous",
    C: "Fearful",
    answer: "B",
  },
  {
    question: "What is the correct spelling?",
    A: "Seperate",
    B: "Separate",
    C: "Seperat",
    answer: "B",
  },
  {
    question: "Which word is a synonym for 'beautiful'?",
    A: "Ugly",
    B: "Attractive",
    C: "Pretty",
    answer: "C",
  },
];
const engC3 = [
  {
    question: "Which word is spelled correctly?",
    A: "Occasion",
    B: "Occassion",
    C: "Occasssion",
    answer: "A",
  },
  {
    question: "What is the past tense of 'begin'?",
    A: "Began",
    B: "Begun",
    C: "Beginned",
    answer: "A",
  },
  {
    question: "Which of the following words is a synonym for 'famous'?",
    A: "Notorious",
    B: "Obscure",
    C: "Renowned",
    answer: "C",
  },
  {
    question: "What is the plural of 'crisis'?",
    A: "Crisises",
    B: "Crises",
    C: "Crisis",
    answer: "B",
  },
  {
    question: "Which word is a synonym for 'difficult'?",
    A: "Easy",
    B: "Challenging",
    C: "Simple",
    answer: "B",
  },
  {
    question: "What is the past participle of 'swim'?",
    A: "Swum",
    B: "Swimmed",
    C: "Swam",
    answer: "A",
  },
  {
    question: "Which of the following words is spelled correctly?",
    A: "Exaggerate",
    B: "Exagerate",
    C: "Exagerrate",
    answer: "A",
  },
  {
    question: "What is the plural of 'child'?",
    A: "Children",
    B: "Childs",
    C: "Childes",
    answer: "A",
  },
  {
    question: "Which word is a synonym for 'brave'?",
    A: "Timid",
    B: "Courageous",
    C: "Fearful",
    answer: "B",
  },
  {
    question: "What is the past tense of 'think'?",
    A: "Thought",
    B: "Thinking",
    C: "Thinked",
    answer: "A",
  },
  {
    question: "Which of the following words is spelled correctly?",
    A: "Environment",
    B: "Envirronment",
    C: "Enviroment",
    answer: "A",
  },
  {
    question: "What is the plural of 'ox'?",
    A: "Oxen",
    B: "Oxes",
    C: "Oxs",
    answer: "A",
  },
  {
    question: "Which word is a synonym for 'generous'?",
    A: "Stingy",
    B: "Bountiful",
    C: "Miserly",
    answer: "B",
  },
  {
    question: "What is the past tense of 'choose'?",
    A: "Chosen",
    B: "Choose",
    C: "Chose",
    answer: "C",
  },
  {
    question: "Which of the following words is spelled correctly?",
    A: "Acheive",
    B: "Achieve",
    C: "Acheeve",
    answer: "B",
  },
  {
    question: "What is the plural of 'goose'?",
    A: "Gooses",
    B: "Geese",
    C: "Geeses",
    answer: "B",
  },
  {
    question: "Which word is a synonym for 'helpful'?",
    A: "Obstructive",
    B: "Beneficial",
    C: "Detrimental",
    answer: "B",
  },
  {
    question: "What is the past tense of 'forget'?",
    A: "Forgot",
    B: "Forgotten",
    C: "Forgetted",
    answer: "A",
  },
  {
    question: "Which of the following words is spelled correctly?",
    A: "Harassment",
    B: "Harassmentt",
    C: "Harrassment",
    answer: "A",
  },
  {
    question: "What is the plural of 'analysis'?",
    A: "Analysises",
    B: "Analyses",
    C: "Analysees",
    answer: "B",
  },
];

const mathC1 = [
  {
    question: "What is 3 + 5?",
    A: "6",
    B: "7",
    C: "8",
    D: "9",
    answer: "C",
  },
  {
    question: "Which number comes before 20?",
    A: "18",
    B: "19",
    C: "20",
    D: "21",
    answer: "B",
  },
  {
    question: "What is 4 * 6?",
    A: "20",
    B: "22",
    C: "24",
    D: "26",
    answer: "C",
  },
  {
    question: "What is 15 ÷ 3?",
    A: "3",
    B: "4",
    C: "5",
    D: "6",
    answer: "C",
  },
  {
    question: "What is 7 * 3?",
    A: "18",
    B: "19",
    C: "20",
    D: "21",
    answer: "D",
  },
  {
    question: "What is 20 ÷ 4?",
    A: "4",
    B: "5",
    C: "6",
    D: "7",
    answer: "B",
  },
  {
    question: "What is 9 + 6?",
    A: "13",
    B: "14",
    C: "15",
    D: "16",
    answer: "C",
  },
  {
    question: "What is 14 - 8?",
    A: "4",
    B: "5",
    C: "6",
    D: "7",
    answer: "C",
  },
  {
    question: "What is 5 * 5?",
    A: "20",
    B: "22",
    C: "24",
    D: "25",
    answer: "D",
  },
  {
    question: "What is 24 ÷ 6?",
    A: "3",
    B: "4",
    C: "5",
    D: "6",
    answer: "B",
  },
  {
    question: "What is 6 * 7?",
    A: "38",
    B: "39",
    C: "40",
    D: "42",
    answer: "D",
  },
  {
    question: "What is 30 ÷ 5?",
    A: "4",
    B: "5",
    C: "6",
    D: "7",
    answer: "B",
  },
  {
    question: "What is 7 + 8?",
    A: "13",
    B: "14",
    C: "15",
    D: "16",
    answer: "C",
  },
  {
    question: "What is 16 - 6?",
    A: "8",
    B: "9",
    C: "10",
    D: "11",
    answer: "C",
  },
  {
    question: "What is 3 * 4?",
    A: "10",
    B: "11",
    C: "12",
    D: "13",
    answer: "C",
  },
  {
    question: "What is 18 ÷ 2?",
    A: "7",
    B: "8",
    C: "9",
    D: "10",
    answer: "C",
  },
  {
    question: "What is 9 + 3?",
    A: "10",
    B: "11",
    C: "12",
    D: "13",
    answer: "C",
  },
  {
    question: "What is 20 - 10?",
    A: "8",
    B: "9",
    C: "10",
    D: "11",
    answer: "C",
  },
  {
    question: "What is 18 ÷ 3?",
    A: "5",
    B: "6",
    C: "7",
    D: "8",
    answer: "B",
  },
  {
    question: "What is 15 * 2?",
    A: "28",
    B: "29",
    C: "30",
    D: "31",
    answer: "C",
  },
];

const mathC2 = [
  {
    question: "What is the square root of 81?",
    A: "7",
    B: "8",
    C: "9",
    D: "10",
    answer: "C",
  },
  {
    question: "Solve for x: 2x + 5 = 17",
    A: "6",
    B: "7",
    C: "8",
    D: "9",
    answer: "B",
  },
  {
    question: "What is the value of π (pi) to two decimal places?",
    A: "3.12",
    B: "3.14",
    C: "3.16",
    D: "3.18",
    answer: "B",
  },
  {
    question:
      "If a triangle has angles measuring 45°, 45°, and 90°, what type of triangle is it?",
    A: "Acute",
    B: "Obtuse",
    C: "Right",
    D: "Isosceles",
    answer: "C",
  },
  {
    question:
      "What is the slope of the line passing through the points (2, 3) and (6, 9)?",
    A: "1",
    B: "2",
    C: "3",
    D: "4",
    answer: "B",
  },
  {
    question: "What is the value of 4! (4 factorial)?",
    A: "12",
    B: "16",
    C: "20",
    D: "24",
    answer: "D",
  },
  {
    question: "Solve for x: 3x - 7 = 11",
    A: "4",
    B: "6",
    C: "8",
    D: "10",
    answer: "B",
  },
  {
    question:
      "What is the area of a circle with radius 5 units? (Use π = 3.14)",
    A: "15.7 sq. units",
    B: "25 sq. units",
    C: "31.4 sq. units",
    D: "78.5 sq. units",
    answer: "C",
  },
  {
    question: "What is the sum of the interior angles of a hexagon?",
    A: "180°",
    B: "360°",
    C: "540°",
    D: "720°",
    answer: "C",
  },
  {
    question: "What is the volume of a cube with side length 3 units?",
    A: "9 cubic units",
    B: "18 cubic units",
    C: "27 cubic units",
    D: "36 cubic units",
    answer: "C",
  },
  {
    question: "What is the value of log₂(8)?",
    A: "2",
    B: "3",
    C: "4",
    D: "5",
    answer: "B",
  },
  {
    question:
      "What is the equation of a line in slope-intercept form if the slope is 3 and the y-intercept is -2?",
    A: "y = 3x - 2",
    B: "y = -2x + 3",
    C: "y = 3x + 2",
    D: "y = -3x - 2",
    answer: "C",
  },
  {
    question: "What is the value of tan(45°)?",
    A: "1",
    B: "0",
    C: "√2",
    D: "2",
    answer: "C",
  },
  {
    question: "If a square has side length 6 units, what is its perimeter?",
    A: "12 units",
    B: "18 units",
    C: "24 units",
    D: "36 units",
    answer: "C",
  },
  {
    question: "What is the solution to the equation x² - 4x + 4 = 0?",
    A: "x = 0",
    B: "x = 2",
    C: "x = 4",
    D: "x = 2 or x = 4",
    answer: "D",
  },
  {
    question: "What is the value of sin(30°)?",
    A: "0",
    B: "0.5",
    C: "1",
    D: "√3/2",
    answer: "B",
  },
  {
    question:
      "What is the surface area of a cylinder with radius 4 units and height 8 units? (Use π = 3.14)",
    A: "128 sq. units",
    B: "192 sq. units",
    C: "256 sq. units",
    D: "384 sq. units",
    answer: "B",
  },
  {
    question: "What is the value of 5^3?",
    A: "125",
    B: "250",
    C: "375",
    D: "500",
    answer: "A",
  },
  {
    question:
      "What is the equation of a circle with center (3, -2) and radius 5?",
    A: "(x - 3)² + (y + 2)² = 5",
    B: "(x + 3)² + (y - 2)² = 25",
    C: "(x - 3)² + (y + 2)² = 25",
    D: "(x + 3)² + (y - 2)² = 5",
    answer: "C",
  },
  {
    question:
      "What is the sum of the first 10 terms of the arithmetic sequence: 3, 7, 11, 15, ...?",
    A: "320",
    B: "360",
    C: "400",
    D: "440",
    answer: "B",
  },
];

const mathC3 = [
  {
    question:
      "Which of the following is a solution to the equation 2x - 3 = 9?",
    A: "x = 4",
    B: "x = 6",
    C: "x = 7",
    D: "x = 9",
    answer: "B",
  },
  {
    question: "What is the value of cos(60°)?",
    A: "0",
    B: "0.5",
    C: "1",
    D: "√3/2",
    answer: "B",
  },
  {
    question:
      "What is the sum of the roots of the quadratic equation x² - 6x + 9 = 0?",
    A: "0",
    B: "3",
    C: "6",
    D: "9",
    answer: "B",
  },
  {
    question: "Which of the following is equivalent to log₄(16)?",
    A: "2",
    B: "3",
    C: "4",
    D: "5",
    answer: "A",
  },
  {
    question:
      "What is the equation of a line perpendicular to y = 2x + 3 and passing through the point (1, 4)?",
    A: "y = -2x + 5",
    B: "y = 2x - 1",
    C: "y = -0.5x + 4.5",
    D: "y = 0.5x + 3.5",
    answer: "A",
  },
  {
    question: "What is the sum of the exterior angles of a polygon?",
    A: "90°",
    B: "180°",
    C: "360°",
    D: "540°",
    answer: "C",
  },
  {
    question: "What is the value of tan(60°)?",
    A: "1",
    B: "√3",
    C: "1/√3",
    D: "1/√3",
    answer: "B",
  },
  {
    question:
      "What is the volume of a cone with radius 4 units and height 6 units? (Use π = 3.14)",
    A: "50.24 cubic units",
    B: "75.36 cubic units",
    C: "100.48 cubic units",
    D: "150.72 cubic units",
    answer: "B",
  },
  {
    question: "What is the value of sin(45°)?",
    A: "0",
    B: "0.5",
    C: "1",
    D: "√2/2",
    answer: "D",
  },
  {
    question:
      "What is the perimeter of a rectangle with length 8 units and width 5 units?",
    A: "26 units",
    B: "30 units",
    C: "32 units",
    D: "36 units",
    answer: "C",
  },
  {
    question:
      "What is the discriminant of the quadratic equation 4x² - 2x + 1 = 0?",
    A: "2",
    B: "4",
    C: "6",
    D: "8",
    answer: "B",
  },
  {
    question:
      "What is the equation of the circle with center (-2, 3) and radius 5?",
    A: "(x + 2)² + (y - 3)² = 25",
    B: "(x - 2)² + (y + 3)² = 5",
    C: "(x + 2)² + (y - 3)² = 5",
    D: "(x - 2)² + (y + 3)² = 25",
    answer: "A",
  },
  {
    question:
      "Which trigonometric ratio is equal to opposite/hypotenuse in a right triangle?",
    A: "Sine",
    B: "Cosine",
    C: "Tangent",
    D: "Cosecant",
    answer: "A",
  },
  {
    question: "What is the solution set of the equation x² - 4x - 5 = 0?",
    A: "{-1, 5}",
    B: "{-1, -5}",
    C: "{1, 5}",
    D: "{1, -5}",
    answer: "A",
  },
  {
    question: "If sin(A) = 0.6 and cos(A) = 0.8, what is the value of tan(A)?",
    A: "0.5",
    B: "0.6",
    C: "0.7",
    D: "0.8",
    answer: "A",
  },
  {
    question:
      "What is the surface area of a sphere with radius 7 units? (Use π = 3.14)",
    A: "615.44 sq. units",
    B: "615.28 sq. units",
    C: "615.12 sq. units",
    D: "614.96 sq. units",
    answer: "A",
  },
  {
    question: "What is the value of log₃(81)?",
    A: "2",
    B: "3",
    C: "4",
    D: "5",
    answer: "B",
  },
  {
    question:
      "What is the nth term of the arithmetic sequence: 3, 7, 11, 15, ...?",
    A: "4n - 1",
    B: "4n + 1",
    C: "4n",
    D: "4n + 3",
    answer: "B",
  },
  {
    question:
      "What is the equation of a parabola with vertex (3, -2) and focus (3, 1)?",
    A: "y = x² + 5",
    B: "y = -x² - 5",
    C: "x = 3",
    D: "y = (1/4)(x - 3)² - 2",
    answer: "D",
  },
  {
    question: "What is the value of 2^(3/2)?",
    A: "2",
    B: "4",
    C: "√2",
    D: "√4",
    answer: "C",
  },
];

const physC2 = [
  {
    question: "Đơn vị SI của dòng điện là gì?",
    A: "Volt",
    B: "Ampere",
    C: "Ohm",
    D: "Watt",
    answer: "B",
  },
  {
    question: "Đơn vị nào sau đây là đơn vị của lực?",
    A: "Newton",
    B: "Watt",
    C: "Joule",
    D: "Volt",
    answer: "A",
  },
  {
    question:
      "Loại năng lượng nào được một vật thể sở hữu do chuyển động của nó?",
    A: "Năng lượng tiềm năng",
    B: "Năng lượng nhiệt",
    C: "Năng lượng động",
    D: "Năng lượng điện",
    answer: "C",
  },
  {
    question: "Công thức tính tốc độ là gì?",
    A: "Vận tốc = Quãng đường / Thời gian",
    B: "Vận tốc = Thời gian / Quãng đường",
    C: "Vận tốc = Quãng đường × Thời gian",
    D: "Vận tốc = Cường độ / Thời gian",
    answer: "A",
  },
  {
    question: "Đơn vị nào sau đây là đơn vị của công suất?",
    A: "Watt",
    B: "Joule",
    C: "Ampere",
    D: "Ohm",
    answer: "A",
  },
  {
    question: "Gia tốc trọng trường trên Trái Đất là bao nhiêu?",
    A: "9.8 m/s²",
    B: "8.8 m/s²",
    C: "10.8 m/s²",
    D: "7.8 m/s²",
    answer: "A",
  },
  {
    question:
      "Nếu lực tác dụng net lên một vật thể là không, thì điều gì xảy ra với tốc độ của vật thể?",
    A: "Nó giảm",
    B: "Nó tăng",
    C: "Nó không thay đổi",
    D: "Nó dao động",
    answer: "C",
  },
  {
    question:
      "Trong số những lựa chọn sau, cái nào không phải là một loại máy đơn giản?",
    A: "Ròng rọc",
    B: "Cần cẩu",
    C: "Đường ống",
    D: "Cầu chì",
    answer: "C",
  },
  {
    question:
      "Quy luật nào sau đây nói rằng mỗi hành động đều có một phản ứng bằng và ngược lại?",
    A: "Định luật Newton thứ nhất",
    B: "Định luật Newton thứ hai",
    C: "Định luật Newton thứ ba",
    D: "Định luật của Coulomb",
    answer: "C",
  },
  {
    question: "Đơn vị đo điện trở là gì?",
    A: "Ohm",
    B: "Volt",
    C: "Ampere",
    D: "Watt",
    answer: "A",
  },
  {
    question: "Đơn vị SI của tần số là gì?",
    A: "Hertz",
    B: "Watt",
    C: "Newton",
    D: "Joule",
    answer: "A",
  },
  {
    question:
      "Trong số những lựa chọn sau, cái nào là đơn vị đo trung bình năng lượng động của các hạt trong một chất?",
    A: "Nhiệt độ",
    B: "Áp suất",
    C: "Mật độ",
    D: "Nhiệt lượng",
    answer: "A",
  },
  {
    question:
      "Quy luật nào nói rằng tổng năng lượng của một hệ thống cô lập không thay đổi qua thời gian?",
    A: "Định luật Newton thứ nhất",
    B: "Định luật Newton thứ hai",
    C: "Định luật bảo toàn năng lượng",
    D: "Định luật của Hooke",
    answer: "C",
  },
  {
    question: "Đơn vị đo điện tích là gì?",
    A: "Ampere",
    B: "Coulomb",
    C: "Ohm",
    D: "Watt",
    answer: "B",
  },
  {
    question: "Đơn vị đo công và năng lượng là gì?",
    A: "Joule",
    B: "Newton",
    C: "Watt",
    D: "Hertz",
    answer: "A",
  },
  {
    question:
      "Trong số những lựa chọn sau, công thức nào tính năng lượng tiềm năng của năng lượng hấp thụ?",
    A: "PT = mgh",
    B: "PT = mv²",
    C: "PT = 1/2mv²",
    D: "PT = mgt",
    answer: "A",
  },
  {
    question:
      "Quy luật nào nói rằng áp suất của một khí nghịch biến với thể tích của nó ở nhiệt độ không đổi?",
    A: "Quy luật Boyle",
    B: "Quy luật Charles",
    C: "Quy luật Gay-Lussac",
    D: "Quy luật của Pascal",
    answer: "A",
  },
  {
    question:
      "Trong số những lựa chọn sau, cái nào không phải là một dạng của bức xạ điện từ?",
    A: "Ánh sáng nhìn thấy",
    B: "Âm thanh",
    C: "Tia X",
    D: "Tia gama",
    answer: "B",
  },
  {
    question: "Đơn vị đo dòng điện là gì?",
    A: "Weber",
    B: "Tesla",
    C: "Henry",
    D: "Ampere",
    answer: "D",
  },
  {
    question: "Quy luật nào nói rằng góc phản xạ bằng góc tới?",
    A: "Định luật Newton thứ nhất",
    B: "Định luật Newton thứ hai",
    C: "Quy luật phản xạ",
    D: "Quy luật của Coulomb",
    answer: "C",
  },
];

const physC3 = [
  {
    question:
      "Loại năng lượng nào được tích trữ trong một vật nâng lên trên cao?",
    A: "Năng lượng cơ học",
    B: "Năng lượng hấp thụ",
    C: "Năng lượng tiềm năng",
    D: "Năng lượng nhiệt",
    answer: "C",
  },
  {
    question: "Công thức nào sau đây đúng để tính tốc độ?",
    A: "v = a * t",
    B: "v = s / t",
    C: "v = m * a",
    D: "v = m / s",
    answer: "B",
  },
  {
    question:
      "Lực tác dụng khi hai vật tiếp xúc trên không gian mà không di chuyển gọi là gì?",
    A: "Lực ma sát",
    B: "Lực hấp dẫn",
    C: "Lực căng",
    D: "Không có lực tác dụng",
    answer: "D",
  },
  {
    question:
      "Lực nào giữ cho một vật chuyển động theo một đường thẳng với vận tốc không đổi?",
    A: "Lực trọng lực",
    B: "Lực căng",
    C: "Lực trở",
    D: "Không có lực nào",
    answer: "D",
  },
  {
    question:
      "Loại năng lượng nào được chuyển đổi thành năng lượng cơ khi bạn chạy?",
    A: "Năng lượng nhiệt",
    B: "Năng lượng hấp thụ",
    C: "Năng lượng điện",
    D: "Năng lượng hóa học",
    answer: "A",
  },
  {
    question:
      "Quy luật nào nói rằng một vật thể sẽ giữ vững trạng thái tĩnh hoặc chuyển động với vận tốc không đổi trừ khi có lực tác động lên nó?",
    A: "Quy luật vạn vật hấp dẫn",
    B: "Quy luật Newton thứ nhất",
    C: "Quy luật Newton thứ hai",
    D: "Quy luật Newton thứ ba",
    answer: "B",
  },
  {
    question: "Công thức nào sau đây đúng để tính lực?",
    A: "F = m / a",
    B: "F = m * v",
    C: "F = m * a",
    D: "F = v / t",
    answer: "C",
  },
  {
    question: "Đơn vị nào được sử dụng để đo lượng chất của một vật?",
    A: "Kilogram",
    B: "Meter",
    C: "Second",
    D: "Coulomb",
    answer: "A",
  },
  {
    question:
      "Năng lượng không thể được tạo ra hoặc hủy diệt, chỉ có thể chuyển đổi từ dạng này sang dạng khác. Điều này phản ánh quy luật nào?",
    A: "Quy luật vạn vật hấp dẫn",
    B: "Quy luật bảo toàn năng lượng",
    C: "Quy luật của Pascal",
    D: "Quy luật Archimedes",
    answer: "B",
  },
  {
    question: "Áp suất được định nghĩa là gì?",
    A: "Lực chia cho diện tích",
    B: "Khối lượng nhân với vận tốc",
    C: "Khối lượng nhân với gia tốc",
    D: "Đoạn đường chia cho thời gian",
    answer: "A",
  },
  {
    question: "Đơn vị nào được sử dụng để đo điện trở?",
    A: "Ohm",
    B: "Volt",
    C: "Ampere",
    D: "Watt",
    answer: "A",
  },
  {
    question:
      "Quy luật nào nói rằng áp suất của một lượng khí ở nhiệt độ không đổi là nghịch biến với thể tích của nó?",
    A: "Quy luật Boyle",
    B: "Quy luật Archimedes",
    C: "Quy luật Pascal",
    D: "Quy luật Charles",
    answer: "A",
  },
  {
    question: "Loại năng lượng nào tồn tại trong hạt nhân của nguyên tử?",
    A: "Năng lượng cơ",
    B: "Năng lượng hấp thụ",
    C: "Năng lượng hạt nhân",
    D: "Năng lượng hóa học",
    answer: "C",
  },
  {
    question:
      "Trong một hệ thống đóng, tổng năng lượng của hệ thống không thay đổi theo thời gian. Đây là một phản ánh của quy luật nào?",
    A: "Quy luật Archimedes",
    B: "Quy luật Coulomb",
    C: "Quy luật Newton thứ nhất",
    D: "Quy luật bảo toàn năng lượng",
    answer: "D",
  },
  {
    question: "Công thức nào sau đây đúng để tính trọng lượng?",
    A: "W = m * a",
    B: "W = m * g",
    C: "W = m / a",
    D: "W = g / m",
    answer: "B",
  },
  {
    question:
      "Năng lượng có thể chuyển đổi giữa các dạng khác nhau, nhưng không thể tạo ra hoặc hủy bỏ. Đây là một phản ánh của quy luật nào?",
    A: "Quy luật Archimedes",
    B: "Quy luật Coulomb",
    C: "Quy luật bảo toàn năng lượng",
    D: "Quy luật Newton thứ nhất",
    answer: "C",
  },
  {
    question: "Đơn vị nào được sử dụng để đo điện áp?",
    A: "Volt",
    B: "Ohm",
    C: "Ampere",
    D: "Watt",
    answer: "A",
  },
  {
    question: "Loại năng lượng nào tồn tại trong một viên nam châm?",
    A: "Năng lượng nhiệt",
    B: "Năng lượng hóa học",
    C: "Năng lượng từ trường",
    D: "Năng lượng điện",
    answer: "C",
  },
  {
    question:
      "Quy luật nào nói rằng ánh sáng phản xạ theo góc tới bằng góc phản xạ?",
    A: "Định luật Newton thứ nhất",
    B: "Định luật Newton thứ hai",
    C: "Quy luật phản xạ",
    D: "Quy luật của Coulomb",
    answer: "C",
  },
];

const techC2 = [
  {
    question:
      "Trong lĩnh vực máy tính, từ viết tắt 'CPU' đại diện cho điều gì?",
    A: "Central Processing Unit",
    B: "Computer Processing Unit",
    C: "Central Processor Unit",
    D: "Control Processing Unit",
    answer: "A",
  },
  {
    question: "Trong Internet, từ viết tắt 'URL' đại diện cho điều gì?",
    A: "Universal Resource Locator",
    B: "Uniform Resource Locator",
    C: "Unified Resource Locator",
    D: "Universal Routing Locator",
    answer: "B",
  },
  {
    question:
      "Định dạng tập tin nào thường được sử dụng để chứa các hình ảnh nén?",
    A: "MP3",
    B: "AVI",
    C: "JPEG",
    D: "TXT",
    answer: "C",
  },
  {
    question: "Từ viết tắt 'PDF' đại diện cho điều gì?",
    A: "Portable Document Format",
    B: "Personal Data File",
    C: "Program Database File",
    D: "Printed Document File",
    answer: "A",
  },
  {
    question: "Trong Excel, hàm SUM() được sử dụng để làm gì?",
    A: "Chia tổng số",
    B: "Cộng các số",
    C: "Trừ các số",
    D: "Nhân các số",
    answer: "B",
  },
  {
    question: "Phần mềm nào được sử dụng để tạo và chỉnh sửa văn bản?",
    A: "PowerPoint",
    B: "Photoshop",
    C: "Word",
    D: "Excel",
    answer: "C",
  },
  {
    question: "Trong một địa chỉ email, ký tự '@' được sử dụng để làm gì?",
    A: "Kết thúc tên người dùng",
    B: "Phân tách tên người dùng và tên miền",
    C: "Kết thúc tên miền",
    D: "Kết thúc tên máy chủ",
    answer: "B",
  },
  {
    question: "Trong lập trình, 'HTML' là viết tắt của gì?",
    A: "Hyperlinks and Text Markup Language",
    B: "Hyper Text Markup Language",
    C: "High Technical Markup Language",
    D: "Hyper Technical Markup Language",
    answer: "B",
  },
  {
    question: "Trong Internet, từ viết tắt 'ISP' đại diện cho điều gì?",
    A: "Internet Service Provider",
    B: "International Service Provider",
    C: "Internal Service Provider",
    D: "Internet Server Provider",
    answer: "A",
  },
  {
    question: "Trong lĩnh vực máy tính, RAM là viết tắt của gì?",
    A: "Random Access Memory",
    B: "Read-Only Memory",
    C: "Random Authorized Memory",
    D: "Read Access Memory",
    answer: "A",
  },
  {
    question: "Định dạng tập tin nào thường được sử dụng để chứa video?",
    A: "TXT",
    B: "MP3",
    C: "AVI",
    D: "JPEG",
    answer: "C",
  },
  {
    question: "Từ viết tắt 'URL' trong Internet đại diện cho điều gì?",
    A: "Uniform Resource Locator",
    B: "Unified Routing Language",
    C: "Unified Resource Locator",
    D: "Uniform Routing Language",
    answer: "A",
  },
  {
    question: "Trong Excel, hàm AVG() được sử dụng để làm gì?",
    A: "Tính trung bình cộng",
    B: "Tính trung bình chia",
    C: "Tính trung bình nhân",
    D: "Tính trung bình trừ",
    answer: "A",
  },
  {
    question: "Phần mềm nào được sử dụng để tạo bảng tính?",
    A: "PowerPoint",
    B: "Photoshop",
    C: "Word",
    D: "Excel",
    answer: "D",
  },
  {
    question: "Trong một địa chỉ email, ký tự '@' được sử dụng để làm gì?",
    A: "Kết thúc tên người dùng",
    B: "Phân tách tên người dùng và tên miền",
    C: "Kết thúc tên miền",
    D: "Kết thúc tên máy chủ",
    answer: "B",
  },
  {
    question: "Trong lập trình, 'HTML' là viết tắt của gì?",
    A: "Hyperlinks and Text Markup Language",
    B: "Hyper Text Markup Language",
    C: "High Technical Markup Language",
    D: "Hyper Technical Markup Language",
    answer: "B",
  },
  {
    question: "Trong Internet, từ viết tắt 'ISP' đại diện cho điều gì?",
    A: "Internet Service Provider",
    B: "International Service Provider",
    C: "Internal Service Provider",
    D: "Internet Server Provider",
    answer: "A",
  },
  {
    question: "Trong lĩnh vực máy tính, RAM là viết tắt của gì?",
    A: "Random Access Memory",
    B: "Read-Only Memory",
    C: "Random Authorized Memory",
    D: "Read Access Memory",
    answer: "A",
  },
  {
    question: "Định dạng tập tin nào thường được sử dụng để chứa video?",
    A: "TXT",
    B: "MP3",
    C: "AVI",
    D: "JPEG",
    answer: "C",
  },
  {
    question: "Từ viết tắt 'URL' trong Internet đại diện cho điều gì?",
    A: "Uniform Resource Locator",
    B: "Unified Routing Language",
    C: "Unified Resource Locator",
    D: "Uniform Routing Language",
    answer: "A",
  },
];

const techC3 = [
  {
    question: "Từ viết tắt 'CPU' trong lĩnh vực máy tính đại diện cho điều gì?",
    A: "Central Processing Unit",
    B: "Computer Processing Unit",
    C: "Central Processor Unit",
    D: "Control Processing Unit",
    answer: "A",
  },
  {
    question: "Trong Internet, từ viết tắt 'URL' đại diện cho điều gì?",
    A: "Universal Resource Locator",
    B: "Uniform Resource Locator",
    C: "Unified Resource Locator",
    D: "Universal Routing Locator",
    answer: "B",
  },
  {
    question:
      "Định dạng tập tin nào thường được sử dụng để chứa các hình ảnh nén?",
    A: "MP3",
    B: "AVI",
    C: "JPEG",
    D: "TXT",
    answer: "C",
  },
  {
    question: "Từ viết tắt 'PDF' đại diện cho điều gì?",
    A: "Portable Document Format",
    B: "Personal Data File",
    C: "Program Database File",
    D: "Printed Document File",
    answer: "A",
  },
  {
    question: "Trong Excel, hàm SUM() được sử dụng để làm gì?",
    A: "Chia tổng số",
    B: "Cộng các số",
    C: "Trừ các số",
    D: "Nhân các số",
    answer: "B",
  },
  {
    question: "Phần mềm nào được sử dụng để tạo và chỉnh sửa văn bản?",
    A: "PowerPoint",
    B: "Photoshop",
    C: "Word",
    D: "Excel",
    answer: "C",
  },
  {
    question: "Trong một địa chỉ email, ký tự '@' được sử dụng để làm gì?",
    A: "Kết thúc tên người dùng",
    B: "Phân tách tên người dùng và tên miền",
    C: "Kết thúc tên miền",
    D: "Kết thúc tên máy chủ",
    answer: "B",
  },
  {
    question: "Trong lập trình, 'HTML' là viết tắt của gì?",
    A: "Hyperlinks and Text Markup Language",
    B: "Hyper Text Markup Language",
    C: "High Technical Markup Language",
    D: "Hyper Technical Markup Language",
    answer: "B",
  },
  {
    question: "Trong Internet, từ viết tắt 'ISP' đại diện cho điều gì?",
    A: "Internet Service Provider",
    B: "International Service Provider",
    C: "Internal Service Provider",
    D: "Internet Server Provider",
    answer: "A",
  },
  {
    question: "Trong lĩnh vực máy tính, RAM là viết tắt của gì?",
    A: "Random Access Memory",
    B: "Read-Only Memory",
    C: "Random Authorized Memory",
    D: "Read Access Memory",
    answer: "A",
  },
  {
    question: "Định dạng tập tin nào thường được sử dụng để chứa video?",
    A: "TXT",
    B: "MP3",
    C: "AVI",
    D: "JPEG",
    answer: "C",
  },
  {
    question: "Từ viết tắt 'URL' trong Internet đại diện cho điều gì?",
    A: "Uniform Resource Locator",
    B: "Unified Routing Language",
    C: "Unified Resource Locator",
    D: "Uniform Routing Language",
    answer: "A",
  },
  {
    question: "Trong Excel, hàm AVG() được sử dụng để làm gì?",
    A: "Tính trung bình cộng",
    B: "Tính trung bình chia",
    C: "Tính trung bình nhân",
    D: "Tính trung bình trừ",
    answer: "A",
  },
  {
    question: "Phần mềm nào được sử dụng để tạo bảng tính?",
    A: "PowerPoint",
    B: "Photoshop",
    C: "Word",
    D: "Excel",
    answer: "D",
  },
  {
    question: "Trong một địa chỉ email, ký tự '@' được sử dụng để làm gì?",
    A: "Kết thúc tên người dùng",
    B: "Phân tách tên người dùng và tên miền",
    C: "Kết thúc tên miền",
    D: "Kết thúc tên máy chủ",
    answer: "B",
  },
  {
    question: "Trong lập trình, 'HTML' là viết tắt của gì?",
    A: "Hyperlinks and Text Markup Language",
    B: "Hyper Text Markup Language",
    C: "High Technical Markup Language",
    D: "Hyper Technical Markup Language",
    answer: "B",
  },
  {
    question: "Trong Internet, từ viết tắt 'ISP' đại diện cho điều gì?",
    A: "Internet Service Provider",
    B: "International Service Provider",
    C: "Internal Service Provider",
    D: "Internet Server Provider",
    answer: "A",
  },
  {
    question: "Trong lĩnh vực máy tính, RAM là viết tắt của gì?",
    A: "Random Access Memory",
    B: "Read-Only Memory",
    C: "Random Authorized Memory",
    D: "Read Access Memory",
    answer: "A",
  },
  {
    question: "Định dạng tập tin nào thường được sử dụng để chứa video?",
    A: "TXT",
    B: "MP3",
    C: "AVI",
    D: "JPEG",
    answer: "C",
  },
  {
    question: "Từ viết tắt 'URL' trong Internet đại diện cho điều gì?",
    A: "Uniform Resource Locator",
    B: "Unified Routing Language",
    C: "Unified Resource Locator",
    D: "Uniform Routing Language",
    answer: "A",
  },
  {
    question: "Trong Excel, hàm AVG() được sử dụng để làm gì?",
    A: "Tính trung bình cộng",
    B: "Tính trung bình chia",
    C: "Tính trung bình nhân",
    D: "Tính trung bình trừ",
    answer: "A",
  },
  {
    question: "Phần mềm nào được sử dụng để tạo bảng tính?",
    A: "PowerPoint",
    B: "Photoshop",
    C: "Word",
    D: "Excel",
    answer: "D",
  },
  {
    question: "Trong một địa chỉ email, ký tự '@' được sử dụng để làm gì?",
    A: "Kết thúc tên người dùng",
    B: "Phân tách tên người dùng và tên miền",
    C: "Kết thúc tên miền",
    D: "Kết thúc tên máy chủ",
    answer: "B",
  },
  {
    question: "Trong lập trình, 'HTML' là viết tắt của gì?",
    A: "Hyperlinks and Text Markup Language",
    B: "Hyper Text Markup Language",
    C: "High Technical Markup Language",
    D: "Hyper Technical Markup Language",
    answer: "B",
  },
  {
    question: "Trong Internet, từ viết tắt 'ISP' đại diện cho điều gì?",
    A: "Internet Service Provider",
    B: "International Service Provider",
    C: "Internal Service Provider",
    D: "Internet Server Provider",
    answer: "A",
  },
  {
    question: "Trong lĩnh vực máy tính, RAM là viết tắt của gì?",
    A: "Random Access Memory",
    B: "Read-Only Memory",
    C: "Random Authorized Memory",
    D: "Read Access Memory",
    answer: "A",
  },
  {
    question: "Định dạng tập tin nào thường được sử dụng để chứa video?",
    A: "TXT",
    B: "MP3",
    C: "AVI",
    D: "JPEG",
    answer: "C",
  },
  {
    question: "Từ viết tắt 'URL' trong Internet đại diện cho điều gì?",
    A: "Uniform Resource Locator",
    B: "Unified Routing Language",
    C: "Unified Resource Locator",
    D: "Uniform Routing Language",
    answer: "A",
  },
];

export const quizHtmlCSS = 
[
  {
      question: "Which HTML element is used to create a form?",
      A: "<form>",
      B: "<input>",
      C: "<button>",
      D: "<label>",
      answer: "A"
  },
  {
      question: "Which HTML element is used to define the largest heading?",
      A: "<heading>",
      B: "<h1>",
      C: "<h6>",
      D: "<header>",
      answer: "B"
  },
  {
      question: "Which HTML element is used to create a horizontal rule?",
      A: "<line>",
      B: "<hr>",
      C: "<break>",
      D: "<hrizontal>",
      answer: "B"
  },
  {
      question: "Which HTML element is used to input data in a form?",
      A: "<input>",
      B: "<text>",
      C: "<form>",
      D: "<textbox>",
      answer: "A"
  },
  {
      question: "Which HTML element is used to create an unordered list?",
      A: "<ol>",
      B: "<ul>",
      C: "<li>",
      D: "<list>",
      answer: "B"
  },
  {
    question: "What does CSS stand for?",
    A: "Cascading Style Sheets",
    B: "Creative Style Sheets",
    C: "Computer Style Sheets",
    D: "Cascading Sheet Styles",
    answer: "A"
  },
  {
      question: "What is the 'font-family' property used for in CSS?",
      A: "Set text color",
      B: "Set font style",
      C: "Set text size",
      D: "Set font for text",
      answer: "D"
  },
  {
      question: "What is the 'margin' property used for in CSS?",
      A: "Set background color for the element",
      B: "Set spacing between elements",
      C: "Set element size",
      D: "Set font for the element",
      answer: "B"
  },
  {
      question: "Which property can be used to center an element horizontally in CSS?",
      A: "align: center;",
      B: "vertical-align: middle;",
      C: "text-align: center;",
      D: "position: center;",
      answer: "C"
  },
  {
      question: "What is the 'background-color' property used for in CSS?",
      A: "Set background color for the element",
      B: "Set text color for the element",
      C: "Set element size",
      D: "Set font for the element",
      answer: "A"
  },
];

export const quizJs = 
[
  {
      question: "JavaScript is a ____ programming language.",
      A: "Client-side",
      B: "Server-side",
      C: "Both client-side and server-side",
      D: "None of the above",
      answer: "C"
  },
  {
      question: "What is JavaScript primarily used for in web development?",
      A: "Creating user interfaces",
      B: "Handling logic and interactions on web pages",
      C: "Designing databases",
      D: "Styling and formatting web pages",
      answer: "B"
  },
  {
      question: "JavaScript was originally developed by which company?",
      A: "Google",
      B: "Microsoft",
      C: "Netscape",
      D: "Oracle",
      answer: "C"
  },
  {
      question: "Which statement about variables in JavaScript is correct?",
      A: "Variables in JavaScript must be declared before use",
      B: "JavaScript does not support variables",
      C: "Variables in JavaScript can be declared without the var, let, or const keyword",
      D: "Variables in JavaScript cannot change value after assignment",
      answer: "C"
  },
  {
      question: "What is the purpose of the alert() function in JavaScript?",
      A: "Displaying a warning message on the browser",
      B: "Creating a confirmation dialog",
      C: "Redirecting the user to another webpage",
      D: "Performing an AJAX call",
      answer: "A"
  },
  {
      question: "In JavaScript, which keyword is used to declare a constant?",
      A: "const",
      B: "let",
      C: "var",
      D: "final",
      answer: "A"
  },
  {
      question: "Which of the following is the correct syntax for a for loop in JavaScript?",
      A: "for (i = 0; i < 5; i++)",
      B: "for (i = 0; i <= 5; i++)",
      C: "for (i = 1; i <= 5; i++)",
      D: "for (i = 1; i < 5; i++)",
      answer: "A"
  },
  {
      question: "What is the purpose of the parseInt() function in JavaScript?",
      A: "Converting a string to an integer",
      B: "Converting a number to a string",
      C: "Rounding a number to the nearest integer",
      D: "Checking if a value is NaN",
      answer: "A"
  },
  {
      question: "In JavaScript, which statement below is correct about declaring a function?",
      A: "function myFunction() {}",
      B: "var myFunction = function() {}",
      C: "def myFunction() {}",
      D: "myFunction: function() {}",
      answer: "A"
  },
  {
      question: "In JavaScript, what is the purpose of the '===' operator?",
      A: "Comparing the values of two variables",
      B: "Comparing the values and data types of two variables",
      C: "Assigning the value of variable A to variable B",
      D: "Checking if variable A is divisible by variable B",
      answer: "B"
  }
];

export const quizJava = 
[
  {
      question: "What is Java?",
      A: "A programming language",
      B: "A type of coffee",
      C: "An operating system",
      D: "A web browser",
      answer: "A"
  },
  {
      question: "Who developed Java?",
      A: "Microsoft",
      B: "Oracle",
      C: "Sun Microsystems",
      D: "Google",
      answer: "C"
  },
  {
      question: "Which of the following is not a feature of Java?",
      A: "Platform Independence",
      B: "Automatic Memory Management",
      C: "Pointers",
      D: "Object-oriented",
      answer: "C"
  },
  {
      question: "What is the keyword used to define a class in Java?",
      A: "class",
      B: "Class",
      C: "cls",
      D: "ClassDef",
      answer: "A"
  },
  {
      question: "Which method is called when an object is created in Java?",
      A: "initialize()",
      B: "start()",
      C: "main()",
      D: "constructor()",
      answer: "D"
  },
  {
      question: "Which of the following is not a primitive data type in Java?",
      A: "int",
      B: "float",
      C: "String",
      D: "boolean",
      answer: "C"
  },
  {
      question: "What is the output of the following code?\n\npublic class Main {\n   public static void main(String[] args) {\n       int x = 5;\n       System.out.println(x++);\n   }\n}",
      A: "5",
      B: "6",
      C: "4",
      D: "Compiler Error",
      answer: "A"
  },
  {
      question: "Which keyword is used to inherit a class in Java?",
      A: "extends",
      B: "inherit",
      C: "implements",
      D: "inherits",
      answer: "A"
  },
  {
      question: "What is the purpose of the 'final' keyword in Java?",
      A: "To declare a constant",
      B: "To indicate that a method cannot be overridden",
      C: "To specify the entry point of a program",
      D: "To prevent a class from being inherited",
      answer: "A"
  },
  {
      question: "Which of the following statements is true about Java?",
      A: "Java programs are compiled into bytecode",
      B: "Java programs are compiled into machine code",
      C: "Java programs are interpreted directly",
      D: "Java programs are executed line by line",
      answer: "A"
  }
];

export const quizDatabase = [
  {
    question: "What is a database?",
    A: "A collection of related data",
    B: "A programming language",
    C: "A type of computer",
    D: "A web browser",
    answer: "A"
  },
  {
    question: "Which of the following is a relational database management system (RDBMS)?",
    A: "MongoDB",
    B: "MySQL",
    C: "Redis",
    D: "Elasticsearch",
    answer: "B"
  },
  {
    question: "What is SQL?",
    A: "Structured Language",
    B: "Structured Query Language",
    C: "Standard Query Language",
    D: "System Query Language",
    answer: "B"
  },
  {
    question: "What is the primary key in a database?",
    A: "A key used for primary operations",
    B: "A unique identifier for each record in a table",
    C: "A key used for backups",
    D: "A key used for encryption",
    answer: "B"
  },
  {
    question: "Which SQL command is used to retrieve data from a database?",
    A: "SELECT",
    B: "UPDATE",
    C: "DELETE",
    D: "INSERT",
    answer: "A"
  },
  {
    question: "What is normalization in database design?",
    A: "Organizing data into tables",
    B: "Removing redundant data",
    C: "Ensuring data consistency",
    D: "All of the above",
    answer: "D"
  },
  {
    question: "Which SQL command is used to add new data to a database?",
    A: "SELECT",
    B: "UPDATE",
    C: "DELETE",
    D: "INSERT",
    answer: "D"
  },
  {
    question: "What is ACID in database transactions?",
    A: "Atomicity, Consistency, Isolation, Durability",
    B: "All Columns In Database",
    C: "Association, Columns, Indexes, Data",
    D: "Atomic, Consistent, Incremental, Durable",
    answer: "A"
  },
  {
    question: "What does CRUD stand for in database operations?",
    A: "Create, Retrieve, Update, Delete",
    B: "Compute, Read, Update, Delete",
    C: "Copy, Read, Update, Drop",
    D: "Create, Read, Undo, Drop",
    answer: "A"
  },
  {
    question: "Which of the following is not a type of database?",
    A: "Relational database",
    B: "NoSQL database",
    C: "Graph database",
    D: "Web browser",
    answer: "D"
  }
];


export const eng = [engC1, engC2, engC3];
export const math = [mathC1, mathC2, mathC3];
export const physics = [physC2, physC3];
export const tech = [techC2, techC3];
